# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '블로그'
email: damidami125@gmail.com
description: 'Blog'
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 'DemiHwang'
github_username: 'DemiHwang'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
# disqus_shortname:  ''

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

plugins:
 - jekyll-coffeescript
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-paginate
 - jekyll-relative-links
 - jekyll-optional-front-matter
 - jekyll-readme-index
 - jekyll-default-layout
 - jekyll-titles-from-headings
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
